#! /bin/csh -f
# simple script to loop through Cedric's output and 
# use fortran fragment ("input") to convert it to GMT readable
# invoke it by typing "loop_cedric filenames* (or whatever)" 

foreach j ($*)
        set i = $j
                echo $i
                cp $i datatopo.txt
                input
                mv datatopo.llt $i.llt
end





#  foreach j (`cat filelist`)

#                echo $j <<EOF

#  EOF
#  end
