#!/bin/bash
#

for d in */ ; do
    echo "$d"
    cp /Users/nmcgregor/Documents/BaltisVallis/files_to_copy_for_data_sets/contour_cedric.gmt $d
    cp /Users/nmcgregor/Documents/BaltisVallis/files_to_copy_for_data_sets/input.f $d
    cp /Users/nmcgregor/Documents/BaltisVallis/files_to_copy_for_data_sets/loop_cedric $d
    cp /Users/nmcgregor/Documents/BaltisVallis/files_to_copy_for_data_sets/loop_cedric2 $d
done
