#! /bin/csh -f
# simple script to loop through files and run GMT script on each
# invoke by typing "loop_cedric2 <filenames>"
foreach j ($*)
        set i = $j
                echo $i
                cp $i datatopo.llt
                contour_cedric.gmt
                mv cedric.dat $i.dat
end
