#!/bin/bash
#

for d in */ ; do
    echo "$d"
    cd "$d"
    gfortran input.f && ls *.txt > txt_filenames.txt 
    cd - 
done

for d in */ ; do
    echo "$d"
    cd "$d"
    input="txt_filenames.txt"
    while IFS= read -r file; do
        csh loop_cedric "$file"
    done < "$input"
    cd - 
done

for d in */ ; do
    echo "$d"
    cd "$d"
    ls *.llt > llt_filenames.txt 
    cd - 
done

for d in */ ; do
    echo "$d"
    cd "$d"
    input="llt_filenames.txt"
    while IFS= read -r file; do
        csh loop_cedric2 "$file"
    done < "$input"
    cd - 
done
